### ISSUE TITLE
Nodemcu vs wemos D1 mini pro

### ISSUE THREAD

**Issue by wazzmolisis** [mrizvic/nodemcu-uart2mqtt#5]
I Recently purchased this: Aideepen WEMOS D1 Mini Pro - 16M Bytes External Antenna Connector ESP8266 WIFI IoT Board https://www.amazon.com/dp/B07333L9VR/ref=cm_sw_r_other_apa_5v4cAbTGR9FHF
Does this item perform the same as the Nodemcu esp8266

**Comment by jumpswitch** [comment]
Yes, because chip is the same (esp8266).

**Comment by wazzmolisis** [comment]
Thanks for all your help. I'm a noob.
